
name: workflow test

on:
  workflow_dispatch:
    inputs:
      data-clean-method:
        description: "Clean method"
        required: true
        default: "all-without-users"
        type: choice
        options:
          - all-without-users
          - spaces
          - space-clusters
          - devices
          - delete-all-data

  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Show GitHub context   
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}   
      if: ${{ inputs.data-clean-method == 'all-without-users' }} && contains('["priyanthabuddhika","herath"]', github.actor)
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      
    - name: Show haspermission   
      run: echo ${{ inputs }}
      shell: bash

