
name: workflow test

on:
  workflow_dispatch
  
env:
  has-permission : contains('["priyanthabuddhika","herath"]', github.actor)
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Show GitHub context   
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}   
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      
    - name: Show haspermission   
      run: echo ${{ env.permission }}
      shell: bash

